### ISSUE TITLE
Shouldn't be a gulp plugin

### ISSUE THREAD

**Issue by sindresorhus** [raulghm/gulp-wp-rev#1]
Should rather be a vanilla node module. Please read the plugins guidelines.

**Comment by raulghm** [comment]
@sindresorhus sorry, do not have much experience writing modules. I try to write the code again;)

**Comment by sindresorhus** [comment]
We're just trying not to create a silo of gulp plugins. This way it can be useful for everyone, not just gulp users :)

**Comment by sindresorhus** [comment]
@raulghm ping
