### ISSUE TITLE
Make regex less greedy for white spaces 

### ISSUE THREAD

**Issue by andredewaard** [raulghm/gulp-wp-rev#3]
Can you make the regex less greedy with white spaces. I had one space on
`wp_enqueue_style( 'custom_style', get_template_directory_uri() . '/css/style.css', false, '99751aae501b70d8edb1be6d827adefd');`
Where you had
`wp_enqueue_style('custom_style', get_template_directory_uri() . '/css/style.css', false, '99751aae501b70d8edb1be6d827adefd');`
That one white space at "_style( 'custom" was the whole issue why it didn't work for me.

**Comment by bjorn2404** [comment]
Agreed, this would make it "compliant" with the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage).
